[package]
name = "extract-browser-url"
version = "0.1.0"
edition = "2024"
rust-version = "1.90.0"
authors = ["flinglin"]
description = "extract browser URL"
license = "MIT"
repository = "https://github.com/Flinglin/extract-browser-url"
documentation = "https://docs.rs/extract-browser-url"
homepage = "https://github.com/Flinglin/extract-browser-url"
keywords = ["browser", "url", "window"]
categories = ["os", "api-bindings", "development-tools"]
readme = "README.md"

[dependencies]
thiserror = {version = "~2.0"}
windows = { version = "~0.62", features = ["Win32_UI_WindowsAndMessaging","Win32_System_Threading","Win32_System_ProcessStatus"] }
uiautomation = { version = "~0.24", features = ["process"] }